---
apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mydemoconfigmap
  namespace: demo
data:
  DEMOENV_SERVICE: "mydemoenvservice.demo.svc.cluster.local"
  PORT: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydemo
  namespace: demo
spec:
  replicas: 4
  selector:
    matchLabels:
      app: mydemo
  template:
    metadata:
      labels:
        app: mydemo
    spec:
      containers:
      - name: mydemo
        image: jpalaparthi/demo:v0.0.2
        env:
        - name: DEMOENV_SERVICE
          valueFrom:
            configMapKeyRef:
              name: mydemoconfigmap
              key: DEMOENV_SERVICE 
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: mydemoconfigmap
              key: PORT 
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: mydemoservice
  namespace: demo
spec:
  selector:
    app: mydemo
  type: LoadBalancer
  ports:
  - port: 8081
    targetPort: 8081





