apiVersion: apps/v1
kind: Deployment
metadata:
  name: myappdeployment
  namespace: dev
  labels:
    type: backend
    environment: development
    app: myappdeployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: mysampleapp
        image: jpalaparthi/samplealpinestage:v0.0.2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080