externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /greet/:name:
    get:
      consumes:
      - application/json
      description: greet with name
      parameters:
      - description: Name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: greet example
      tags:
      - greet
  /helloworld:
    get:
      consumes:
      - application/json
      description: call helloworld it returns helloworld
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: helloworld example
      tags:
      - helloworld ping
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
