---
apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: demo
data:
  DBCONN: aG9zdD1sb2NhbGhvc3QgdXNlcj1wb3N0Z3JlcyBwYXNzd29yZD1wb3N0Z3JlcyBkYm5hbWU9Y29udGFjdHNiZCBwb3J0PTU1NDMyIHNzbG1vZGU9ZGlzYWJsZSBUaW1lWm9uZT1Bc2lhL1NoYW5naGFpCg==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydemenv
  namespace: demo
spec:
  replicas: 4
  selector:
    matchLabels:
      app: mydemenv
  template:
    metadata:
      labels:
        app: mydemenv
    spec:
      containers:
      - name: mydemenv
        image: jpalaparthi/demoenv:v0.0.1
        env:
        - name: DBCONN
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: DBCONN 
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mydemoenvservice
  namespace: demo
spec:
  selector:
    app: mydemenv
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080




