---
apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigmap
  namespace: demo
data:
  DBCONN: "host=localhost user=postgres password=postgres dbname=contactsbd port=55432 sslmode=disable TimeZone=Asia/Shanghai"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydemenv
  namespace: demo
spec:
  replicas: 4
  selector:
    matchLabels:
      app: mydemenv
  template:
    metadata:
      labels:
        app: mydemenv
    spec:
      containers:
      - name: mydemenv
        image: jpalaparthi/demoenv:v0.0.1
        env:
        - name: DBCONN
          valueFrom:
            configMapKeyRef:
              name: myconfigmap
              key: DBCONN 
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mydemoenvservice
  namespace: demo
spec:
  selector:
    app: mydemenv
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080



